# Generated by Django 2.1 on 2018-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='description',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='record',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
