# Generated by Django 2.1 on 2018-09-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0002_auto_20180919_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('twilio_call_id', models.CharField(blank=True, max_length=64, null=True)),
                ('caller_number', models.CharField(blank=True, max_length=32, null=True)),
                ('caller_name', models.CharField(blank=True, max_length=32, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.IntegerField(blank=True, null=True)),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='voip.Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='calls',
            name='number',
        ),
        migrations.DeleteModel(
            name='Calls',
        ),
    ]
