# Generated by Django 2.1 on 2018-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0003_auto_20180919_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='recording_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
